### ISSUE TITLE
When viewed on notepad, all the multiple lines in the Hexchat log files all appear to be on one line.

### ISSUE THREAD

**Issue by fancyGitHubName** [hexchat/hexchat#1834] opened 2016-10-09 05:51 UTC
I do believe this is because of the conventions Hexchat uses when signifying a new line.
See, the way notepad understands a newline is by the two characters CR and LF in succession but the way that Hexchat is putting in newlines into the logs is just by a mere LF. This is problematic for users of notepad. 

The way that I would suggest to fix this is by just merely making sure that the newlines within the log files of Hexchat are signified by both required characters, that is, with CR+LF.

**Comment by kernelpanic3** [comment] 2016-10-09 05:55
Well, really you shouldn't be using Notepad for anything when there's far better text editors out there. ;)

Anyway, this is a side effect of HexChat using Unix line endings rather than the DOS ones that Notepad expects. I guess it could be fixed by having it use different line endings depending on the OS?

**Comment by Arnavion** [comment] 2016-10-09 09:35
Please search for existing issues before opening new ones.

Duplicate of #1675

**Closed by Arnavion** 2016-10-09 09:35 UTC
