### ISSUE TITLE
[Feature Request] Maximize/Focus HexChat Window whenever you Click on Balloon Notification

### ISSUE THREAD

**Issue by pretodor** [hexchat/hexchat#1801] opened 2016-08-22 14:54 UTC
_This may be specific to the Cinnamon DE._

I would like to ask the devs to implement the following feature:
Imagine you have Hexchat minimized in the system tray and you receive a balloon notification because somebody has mentioned you. When you click on the balloon, the HexChat window will get maximized. 

Think of the way Spotify handles notifications.

**Comment by TingPing** [comment] 2016-08-22 16:45
This is basically a duplicate of #1768

**Closed by TingPing** 2016-08-22 16:45 UTC

**Comment by pretodor** [comment] 2016-08-22 16:48
Apologies for posting a duplicate @TingPing and thanks for providing us with the necessary steps to implement this behaviour.
