### ISSUE TITLE
Leading space in URL causes program crash

### ISSUE THREAD

**Issue by RollingStar** [hexchat/hexchat#1586] opened 2016-01-15 23:46 UTC
On WIndows 10 x64, Hexchat x64 2.10.2: 

1. Open the network list
2. add a server called "example-space"
3. edit
4. change the server to

```
 example.com
^leading space
```

Make sure it starts with a space: `> example.com`. Try to connect to the server. After around 5 attempts, the entire program crashes. As far as I can tell this does not happen without the space; Hexchat merely fails to connect.

According to [this](https://stackoverflow.com/questions/497908/is-a-url-allowed-to-contain-a-space), spaces don't belong in URLs anyway. Maybe Hexchat can strip them out?

**Comment by TingPing** [comment] 2016-01-15 23:50
Duplicate of #600

**Closed by TingPing** 2016-01-15 23:50 UTC
