### ISSUE TITLE
Automatically try to reconnect on "SSL handshake timed out" error

### ISSUE THREAD

**Issue by VarunAgw** [hexchat/hexchat#1526] opened 2015-10-27 18:18 UTC
Since I've started using SSL, I am gettting this error quite often. My internet connection is not very good and it keeps disconnecting. Most of the time, it reconnects automatically but sometime it doesn't after getting this error. It will be better if HexChat can try reconnecting again automatically on this error

**Comment by TingPing** [comment] 2015-10-27 18:38
Duplicate of #475

**Closed by TingPing** 2015-10-27 18:38 UTC
