### ISSUE TITLE
Auto-reconnect fails sometimes if proxy doesn't work

### ISSUE THREAD

**Issue by iyx** [hexchat/hexchat#1318] opened 2015-03-14 17:28 UTC
> SOCKS Proxy failed to connect to host (error 3).
> Proxy traversal failed.
> Stopped previous connection attempt (pid=20632)

At first hexchat tries to reconnect as usual, but if proxy is down for a prolonged time it eventually fails and stops at this error. No more connection tries afterwards.

**Comment by Arnavion** [comment] 2015-03-14 18:44
Duplicate of #849

**Closed by Arnavion** 2015-03-14 18:44 UTC
