### ISSUE TITLE
Indicator icon dosen't work on Pantheon

### ISSUE THREAD

**Issue by bil-elmoussaoui** [hexchat/hexchat#1394] opened 2015-06-11 09:21 UTC
Pantheon is based on Ubuntu, as you can see here [elementary OS](www.elementary.io)
The indicator icon is not working, all other indicators works fine!

**Comment by TingPing** [comment] 2015-06-11 09:28
Duplicate of #1235

**Closed by TingPing** 2015-06-11 09:28 UTC

**Comment by bil-elmoussaoui** [comment] 2015-06-11 09:31
Well, it's not the same distro, nothing is the same! KDE have a different library to show/hide indicators.

**Comment by TingPing** [comment] 2015-06-11 10:47
Well the title is very different but the solution for both is to add Appindicator support.
