### ISSUE TITLE
HexChat-2.11.0-x64-1d8dd50 crashes when win7 loses network connectivity

### ISSUE THREAD

**Issue by berrythesoftwarecodeprogrammar** [hexchat/hexchat#1519] opened 2015-10-24 08:56 UTC
this is also the first hexchat version ive tried which required visual c++ 2015. i have the x64 and x86 versions of 2012,2013,2015 installed. when my wifi dies, hexchat crashes

**Comment by Arnavion** [comment] 2015-10-24 10:04
Duplicate of #600

**Closed by Arnavion** 2015-10-24 10:04 UTC
