### ISSUE TITLE
Auto-copy of selected text is broken.

### ISSUE THREAD

**Issue by deckblad** [hexchat/hexchat#1290] opened 2015-02-09 18:54 UTC
Auto-copy of selected text is broken. A proper example would be from mIRC:

Correct: 
User selects text
mIRC copies selected text to clipboard
mIRC deselects previously selected text.

Incorrect:
User selects text in Hexchat channel buffer
Hexchat copies selected text to clipboard
Hextchat leaves buffer text selected
User switches to a different program
User copies some other text to clipboard
User switches back to Hexchat
Hexchat copies originally selected text to clipboard
Hexchat leaves selection on text in buffer
User pastes what they think will be the text from another program, hits enter, is laughed at by friends for posting text from the channel to the channel.

Solution: Hexchat should, after dumping selected text to clipboard, clear any selection from the channel buffer.

**Comment by TingPing** [comment] 2015-02-09 19:04
Duplicate of #943

**Closed by TingPing** 2015-02-09 19:04 UTC
