### ISSUE TITLE
Crash on close

### ISSUE THREAD

**Issue by alexandrevicenzi** [hexchat/hexchat#2270] opened 2018-11-09 10:54 UTC
HexChat crash when I close it.
This started after I loaded a custom python plugin that I was working on.
Even if the plugin is not loaded HexChat still crash.

                Stack trace of thread 2900:
                #0  0x00007f119ea7153f raise (libc.so.6)
                #1  0x00007f119ea5b895 abort (libc.so.6)
                #2  0x00007f118cd38747 n/a (libpython3.7m.so.1.0)
                #3  0x00007f118cd3875e Py_FatalError (libpython3.7m.so.1.0)
                #4  0x00007f118cd3a9bb n/a (libpython3.7m.so.1.0)
                #5  0x00007f118cf06d6e Py_FinalizeEx (libpython3.7m.so.1.0)
                #6  0x00007f118f4828a6 hexchat_plugin_deinit (python.so)
                #7  0x000055fccea77a86 n/a (hexchat)
                #8  0x000055fccea79ec1 plugin_kill_all (hexchat)
                #9  0x000055fccea675a1 hexchat_exit (hexchat)
                #10 0x000055fccea3e2db mg_open_quit_dialog (hexchat)
                #11 0x000055fccea3e44a n/a (hexchat)
                #12 0x00007f119f3d1e9d _gtk_marshal_BOOLEAN__BOXED (libgtk-x11-2.0.so.0)
                #13 0x00007f119f84dc9d g_closure_invoke (libgobject-2.0.so.0)
                #14 0x00007f119f861203 n/a (libgobject-2.0.so.0)
                #15 0x00007f119f8699a3 g_signal_emit_valist (libgobject-2.0.so.0)
                #16 0x00007f119f86a923 g_signal_emit (libgobject-2.0.so.0)
                #17 0x00007f119f50611c gtk_widget_event_internal (libgtk-x11-2.0.so.0)
                #18 0x00007f119f3d011b gtk_main_do_event (libgtk-x11-2.0.so.0)
                #19 0x00007f119f222f70 gdk_event_dispatch (libgdk-x11-2.0.so.0)
                #20 0x00007f119f76c26d g_main_context_dispatch (libglib-2.0.so.0)
                #21 0x00007f119f76c638 n/a (libglib-2.0.so.0)
                #22 0x00007f119f76c962 g_main_loop_run (libglib-2.0.so.0)
                #23 0x00007f119f3cee4f gtk_main (libgtk-x11-2.0.so.0)
                #24 0x000055fccea2b9ed fe_main (hexchat)
                #25 0x000055fccea1faa8 main (hexchat)
                #26 0x00007f119ea5d413 __libc_start_main (libc.so.6)
                #27 0x000055fccea1fbee _start (hexchat)
                
                Stack trace of thread 2902:
                #0  0x00007f119eb2b371 __poll (libc.so.6)
                #1  0x00007f119f76c5a6 n/a (libglib-2.0.so.0)
                #2  0x00007f119f76c6d0 g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007f119f76c721 n/a (libglib-2.0.so.0)
                #4  0x00007f119f79548a n/a (libglib-2.0.so.0)
                #5  0x00007f119ec0758e start_thread (libpthread.so.0)
                #6  0x00007f119eb36593 __clone (libc.so.6)
                
                Stack trace of thread 2903:
                #0  0x00007f119eb2b371 __poll (libc.so.6)
                #1  0x00007f119f76c5a6 n/a (libglib-2.0.so.0)
                #2  0x00007f119f76c962 g_main_loop_run (libglib-2.0.so.0)
                #3  0x00007f119f96479a n/a (libgio-2.0.so.0)
                #4  0x00007f119f79548a n/a (libglib-2.0.so.0)
                #5  0x00007f119ec0758e start_thread (libpthread.so.0)
                #6  0x00007f119eb36593 __clone (libc.so.6)

**Comment by alexandrevicenzi** [comment] 2018-11-09 13:17
HexChat 2.14.2
Fedora 29
Linux 4.18.16-300.fc29.x86_64

**Comment by TingPing** [comment] 2018-11-09 22:21
Duplicate of #2237

**Closed by TingPing** 2018-11-09 22:21 UTC
Labels: bug, plugin
