### ISSUE TITLE
Migrating to GDBus

### ISSUE THREAD

**Issue by qarkai** [hexchat/hexchat#2156] opened 2018-03-28 07:49 UTC
According to [freedesktop.org](https://www.freedesktop.org/wiki/Software/DBusBindings) DBus-GLib is obsolete and [new] applications should use [GDBus](https://developer.gnome.org/gio/stable/ch35.html). Consider [migrating](https://developer.gnome.org/gio/stable/ch35.html) to GDBus.

**Comment by TingPing** [comment] 2018-03-28 22:14
Duplicate of #252

**Closed by TingPing** 2018-03-28 22:14 UTC
