### ISSUE TITLE
Install fails on Windows Server 2012r2

### ISSUE THREAD

**Issue by ragnar76** [hexchat/hexchat#1623] opened 2016-02-27 15:53 UTC
as subject says, it fails while installing on 2012r2. An error box appears saying (translated from german) "a redirect changes from unsecure to secure" and stops after it.

**Comment by tomek** [comment] 2016-02-27 16:19
try downloading it using different browser - hc itself works fine on srv2012r2:

![ss 2016-02-27 at 05 16 48](https://cloud.githubusercontent.com/assets/277443/13373947/4253a08e-dd76-11e5-86c5-794620485b8a.png)

**Comment by TingPing** [comment] 2016-02-27 16:40
Duplicate of #1268

**Closed by TingPing** 2016-02-27 16:40 UTC
