### ISSUE TITLE
Don't allow long passwords to be entered

### ISSUE THREAD

**Issue by danielzgtg** [hexchat/hexchat#2425] opened 2020-01-12 09:59 UTC
#1296 has been open for 5 years now. There have been numerous issues created by users surprised by this problem and it is frustrating to debug: #1968 #2074 #2370 znc/znc#942 znc/znc#1704. While we wait for #1994 to get merged and fix the underlying problem, we can improve the UX earlier to lessen its impact.

A way to do this is by showing an error dialog and refusing to save the server settings if the password is longer than 85 characters.

**Comment by TingPing** [comment] 2020-01-12 18:02
Duplicate of #1296

If somebody is going to dedicate time to this they can just fix it, no need for dialogs.

**Closed by TingPing** 2020-01-12 18:02 UTC
