### ISSUE TITLE
Microsoft Store version still on 2.14.2

### ISSUE THREAD

**Issue by superusercode** [hexchat/hexchat#2439] opened 2020-03-01 00:56 UTC
![image](https://user-images.githubusercontent.com/60588434/75617468-8f0ef700-5b2d-11ea-9131-fac878649209.png)
as of 2/29 from trial install

**Comment by TingPing** [comment] 2020-03-01 04:08
Duplicate of #2411

**Closed by TingPing** 2020-03-01 04:08 UTC
