### ISSUE TITLE
Embed images

### ISSUE THREAD

**Issue by madprops** [hexchat/hexchat#1780] opened 2016-07-26 14:14 UTC
It would be nice if it was possible to to embed images when an image link is posted. Scaled to a limited size, but big enough to allow people to see what the image is about, and sometimes making them not even click on it at all. 

Discord has this for example. 90% of the time I don't have to click on it to see them bigger. But when I do it zooms right there inside the application. Also obviously you can click the link to open it in the browser.

![discord_2016-07-26_08-13-10](https://cloud.githubusercontent.com/assets/206498/17141330/e8930220-5308-11e6-9c95-94ede01eafb1.jpg)

Probably not easy to do, but it would bring Hexchat to more modern standards.

**Comment by TingPing** [comment] 2016-07-26 14:17
Duplicate of #1285

**Closed by TingPing** 2016-07-26 14:17 UTC
