### ISSUE TITLE
Server passwords are truncated at 85 characters.

### ISSUE THREAD

**Issue by miniCruzer** [hexchat/hexchat#2074] opened 2017-10-13 05:14 UTC
Verified with the Raw Log, whether sent with the `/SERVER` command or saved in the network list, HexChat will only send the first 85 characters when sending RFC 1459 PASS to the IRC server.

In this case I'm working with ZNC/weechat-relay, and I was able to verify that the server is only receiving 85 characters as well. 

I see this is referenced in #1296

**Comment by TingPing** [comment] 2017-10-13 05:51
Duplicate of #1296

**Closed by TingPing** 2017-10-13 05:51 UTC
