### ISSUE TITLE
Hide Join/Part Messages option isn't sticky

### ISSUE THREAD

**Issue by Strykar** [hexchat/hexchat#1597] opened 2016-01-29 16:15 UTC
The `Hide Join/Part Messages` option via the right click context menu on channel names will go back to showing Joins/Parts in the channel upon restarting Hexchat. The expected behavior would be to remember the flag set on restart

**Comment by TingPing** [comment] 2016-01-29 16:25
Duplicate of #1134

**Closed by TingPing** 2016-01-29 16:25 UTC
