### ISSUE TITLE
Arbitrary password limit - is there any point?

### ISSUE THREAD

**Issue by Tea23** [hexchat/hexchat#1413] opened 2015-07-01 17:58 UTC
I discovered that HexChat has an arbitrary password character limit of 86 when I was playing around with Twirc (https://github.com/benjojo/TwIRC) which gives a JSON string to be passed to the server as a password containing all the Twitter API information stuff. It exceeds 86 characters.

I'm not a programmer of any calibre but I found the array where the character limit is defined and simply changed it to 9999 and recompiled. HexChat has operated normally ever since and my connection to Twirc works fine.

I suppose in very few cases a password for IRC will ever greatly exceed 86 chars but is it good practice to make decisions like this seemingly *just because* adjusting it only suits niche cases?

Is there actually any point in limiting passwords to an arbitrary amount? What's the problem with allowing as many characters as the user wishes? I am honestly just interested to hear the reasoning behind setting and keeping to arbitrary limits.

**Comment by bendem** [comment] 2015-07-01 18:04
For the lazy ones, the line is [here](https://github.com/hexchat/hexchat/blob/master/src/common/hexchat.h#L496)

**Comment by Arnavion** [comment] 2015-07-01 19:57
The RFC defines a max line length of 510 for a line. Even if you assume the entire line is the password (usually it isn't) the max length could be 510. Then again, the network's auth protocol could support passwords split across lines, so really the limit is arbitrary.

As for the reason it's 86, you'll see the line is unchanged since bv imported the WDK sources. In fact, it's been like that ever since the first commit of the file in xchat: http://sourceforge.net/p/xchat/svn/2/tree/src/common/xchat.h Who knows what zed was thinking when he did it...

**Comment by TingPing** [comment] 2015-07-01 21:08
Duplicate of #1296

**Closed by TingPing** 2015-07-01 21:08 UTC
