### ISSUE TITLE
hexchat dont update /names with inspircd v3

### ISSUE THREAD

**Issue by sacredland** [hexchat/hexchat#2357] opened 2019-08-01 01:03 UTC
on inspircd v3 ircd, hexchat dont update the nicklist with status without doing /names.

**Comment by TingPing** [comment] 2019-08-01 06:00
Sounds like a duplicate of #2271

**Closed by TingPing** 2019-08-01 06:00 UTC

**Comment by sacredland** [comment] 2019-08-03 00:18
yeah but how can i fix it without a new release?
