### ISSUE TITLE
Hexchat crashes when losing internet access

### ISSUE THREAD

**Issue by mzxrules** [hexchat/hexchat#2215] opened 2018-07-09 04:16 UTC
Version 2.14.1, Windows x64 build, but I've had this problem with an older version. The crash does not occur immediately, for me it took probably about 20-30 minutes of no access to the internet, when attempting to connect to 4 different servers.

Faulting application name: hexchat.exe, version: 2.14.1.0, time stamp: 0x5aa88afc
Faulting module name: ucrtbase.dll, version: 10.0.17134.1, time stamp: 0x587decd7
Exception code: 0xc0000409
Fault offset: 0x000000000006d088
Faulting process id: 0x56fc

**Comment by SoniEx2** [comment] 2018-07-16 23:52
can you reproduce this with 1 server and faster reconnect delays?

**Comment by TingPing** [comment] 2018-07-17 14:19
Duplicate of #600

**Closed by TingPing** 2018-07-17 14:20 UTC
