### ISSUE TITLE
Lack of character set fallback

### ISSUE THREAD

**Issue by DataBeaver** [hexchat/hexchat#1939] opened 2017-01-23 12:53 UTC
I just migrated from X-chat to hexchat and immediately noticed that character set fallback is missing.  After some searches I found that it was removed in commit 5749c53.  I have several channels where some people still talk ISO-8859-1 even though most use UTF-8.  Regardless of which character set I select I will see some incorrect characters.  And because I want to talk UTF-8 I can't really select anything else.

Please consider adding back the character set fallback, perhaps as an explicit option.

**Comment by Arnavion** [comment] 2017-01-23 16:23
Duplicate of #1636

**Closed by Arnavion** 2017-01-23 16:23 UTC
