### ISSUE TITLE
Remember sidebar width

### ISSUE THREAD

**Issue by madprops** [hexchat/hexchat#1781] opened 2016-07-30 15:57 UTC
Right now Hexchat in Windows remembers the window's width and height when I reopen it, and even the position of the user's area relative to the channel's area (I have channels on top and users on the bottom, in a sidebar at the right) but it doesn't remember the width of the sidebar and I have to adjust it everytime I open it again. It would be nice if it remembered that.

**Comment by Arnavion** [comment] 2016-07-30 17:34
Duplicate of #748

**Closed by Arnavion** 2016-07-30 17:34 UTC
