### ISSUE TITLE
Suggestion: Option to keep hexchat from opening twice or more? 

### ISSUE THREAD

**Issue by yolarrydabomb** [hexchat/hexchat#1315] opened 2015-03-12 18:08 UTC
Sometimes I forget hexchat is even on the taskbar and open a whole new program again. Would be nice if I did open the program it will only open the one on the taskbar.

**Comment by TingPing** [comment] 2015-03-12 21:10
Duplicate of #252

**Closed by TingPing** 2015-03-12 21:10 UTC
