### ISSUE TITLE
Build hexchat for mac osx

### ISSUE THREAD

**Issue by paladox** [hexchat/hexchat#1909] opened 2016-12-25 23:16 UTC
Hi please could hexchat be built for mac osx too please? I tried brew but it has old versions of hexchat expecially if I want the .app file.

I tried building hexchat but it fails.

**Comment by TingPing** [comment] 2016-12-25 23:37
Duplicate of #1858

**Comment by TingPing** [comment] 2016-12-25 23:38
> I tried brew but it has old versions of hexchat 

They have the latest release.

**Closed by TingPing** 2016-12-25 23:37 UTC

**Comment by paladox** [comment] 2016-12-25 23:48
they have 2.12.3 not 2.13.4 + they did not build the latest hexchat with bundle so I have to run bash to start hexchat.

**Comment by paladox** [comment] 2016-12-25 23:52
tahst brew cask install hexchat that has the old hexchat version 2.10 but it has the .app file which dosent require bash. Whereas brew install hexchat has a shell script that starts hexchat 2.12.3.

**Comment by TingPing** [comment] 2016-12-25 23:53
I wasn't talking about cask, I meant homebrew proper in the gui repo.

**Comment by paladox** [comment] 2016-12-25 23:58
Oh this one brew install hexchat?

I did that one but it dosent have the .app file. Which means I have to use bash to start hexchat.

**Comment by TingPing** [comment] 2016-12-26 07:23
Indeed.

**Comment by paladox** [comment] 2016-12-26 13:00
Oh, how can I build the bundle please as I tryed to follow your docs but make is failing

**Comment by TingPing** [comment] 2016-12-26 13:12
> make is failing

Step one is to give useful information.
