### ISSUE TITLE
Crash during channel search

### ISSUE THREAD

**Issue by walugo** [hexchat/hexchat#1650] opened 2016-03-19 04:27 UTC
Recreated 3 times by following steps:
Join Freenode Server
Server Menu->List of Channels.... 
"BSD" in 'find' form, press search
Sort by users, descending
Join #openbsd (via doubleclick)
Join #pcbsd (via doubleclick)
Change 'find' form to contain "pcbsd", press search
Join #pcbsd-dev (via doubleclick)
Change 'find' form to contain "perl", press search
Crashes immediately.

OS X Crash report attached
[crashreport3-19-16.txt](https://github.com/hexchat/hexchat/files/180636/crashreport3-19-16.txt)

**Comment by TingPing** [comment] 2016-03-19 13:37
Duplicate of #1193

**Closed by TingPing** 2016-03-19 13:37 UTC
