### ISSUE TITLE
Userlist button editing on Windows

### ISSUE THREAD

**Issue by ZetaRift** [hexchat/hexchat#1328] opened 2015-03-23 01:38 UTC
Unlike the linux version of Hexchat, the window to edit userlist buttons don't have the "Move Up" and "Move Down" buttons.

**Comment by TingPing** [comment] 2015-03-23 12:33
Shift+up/down. This applies to most of the settings dialogs.

Duplicate of #1288

**Closed by TingPing** 2015-03-23 12:33 UTC
