### ISSUE TITLE
Network-specific 3rd nick choice

### ISSUE THREAD

**Issue by KeeperB5** [hexchat/hexchat#1788] opened 2016-08-11 04:57 UTC
Global user information has three nick choices, network specific ones have two. Should connection to irc network be lost twice in short time, global 3rd nick choice will be used even if "Use global user information" is unchecked.

This issue remains in version 2.12.1.

**Comment by TingPing** [comment] 2016-08-11 06:13
Will just call this a duplicate of #820

**Closed by TingPing** 2016-08-11 06:13 UTC
