### ISSUE TITLE
irc association

### ISSUE THREAD

**Issue by bingoxo** [hexchat/hexchat#2334] opened 2019-05-05 12:36 UTC
in my laptop i installed the windows store version and it detects irc links if click on them in my browser , on my desktop however where i installed the "normal" version , it doesn't seem to detect them nor does it show when i want to add it in default apps 

I am using windows 10

**Comment by TingPing** [comment] 2019-05-05 18:37
Duplicate of #1277

**Closed by TingPing** 2019-05-05 18:37 UTC
