### ISSUE TITLE
Duplicate apple menu item on OS X 10.10.5

### ISSUE THREAD

**Issue by ilkka** [hexchat/hexchat#1495] opened 2015-10-01 06:25 UTC
On latest Yosemite, when the Hexchat window is focused there are two system menu entries in the menu bar:

![2015-10-01 at 09 24](https://cloud.githubusercontent.com/assets/1549/10214162/466cbbce-681e-11e5-831e-a760875b6442.png)

The leftmost, larger one is the real system menu, while the second is empty.

**Comment by KindOne-** [comment] 2015-10-01 06:50
Duplicate of #994

**Closed** 2015-10-01 07:44 UTC
Labels: duplicate
