### ISSUE TITLE
Crash when awaking from hibernation on Windows 10

### ISSUE THREAD

**Issue by joranbosscher** [hexchat/hexchat#1479] opened 2015-09-12 14:42 UTC
My Hexchat seems to crash every time I start the computer again if it was open when I hibernated it. 
I'm on Hexchat 2.10.2 and Windows 10 Pro x64. I am not using any plugins except the update checker.

**Comment by TingPing** [comment] 2015-09-12 15:32
Duplicate of #600

**Closed by TingPing** 2015-09-12 15:32 UTC
