### ISSUE TITLE
hexchat miss selecting RTL language 

### ISSUE THREAD

**Issue by Seeder101** [hexchat/hexchat#1846] opened 2016-10-17 20:38 UTC
Hi, I noticed this problem long time ago, and its still there with RTL languages 
this is a clear screenshot of what it looks like when you try to select an arabic text 

![selection_016](https://cloud.githubusercontent.com/assets/7802688/19454633/94dbefd8-94c2-11e6-82c3-54df4ea2a76b.png)

unlike with english 

![selection_017](https://cloud.githubusercontent.com/assets/7802688/19454665/b7a1b5ca-94c2-11e6-8014-23cb8e16a9d7.png)

what's the problem here?

thank you

**Comment by TingPing** [comment] 2016-10-17 20:54
Duplicate of #692

**Closed by TingPing** 2016-10-17 20:54 UTC
