### ISSUE TITLE
Config Network List between two Operative Systems

### ISSUE THREAD

**Issue by mossarelli** [hexchat/hexchat#1569] opened 2015-12-17 19:28 UTC
I'm running Windows 7 and Linux Mint with HexChat 2.10.2 for Windows and whatever version of HexChat that is maintained on Mint's repo. at the moment (2.9.6).

I run HexChat in portable mode from a Dropbox folder which saves all my configs and logs. In the Mint OS, I run HexChat as the native program and not through Wine, but I hotlinked the config folder to the ~/.config/hexchat folder so that both OSs uses the same config files.

When using the Windows program, everything works fine. But when I switch to Mint, all the entries in the server list in the network list gets a little white space after the name. When you click to edit a server entry, the list of Servers, Autojoin channels also get a white space after each name or channel, rendering them all null and HexChat refuses to connect.

I repeat: This only happens when going from Windows to Mint, not from Mint to Windows.

I'm going to attach pictures describing the problem.
Windows 7:
![list](https://cloud.githubusercontent.com/assets/2856049/11879597/a5364088-a4fc-11e5-8ed4-f12b47c6ee8a.jpg)
Linux Mint:
![grab](https://cloud.githubusercontent.com/assets/2856049/11879797/d1ed866c-a4fd-11e5-9727-7192c59c7120.jpg)

I know this has something to do with encoding issues going from UTF-8 to ASCII and back and such. I'm just curious as to where it happens between the Windows build and the Linux Build.

Please provide an alternative solution for sharing config files if there is something that I've overlooked.

**Comment by TingPing** [comment] 2015-12-17 19:54
> I know this has something to do with encoding issues going from UTF-8 to ASCII and back and such. I'm just curious as to where it happens between the Windows build and the Linux Build.

Nope, just newline differences, run `dos2unix` on the config files and all is good.

Duplicate of #834

**Closed by TingPing** 2015-12-17 19:54 UTC
