### ISSUE TITLE
Extra words to highlight doesn't work if string starts with @

### ISSUE THREAD

**Issue by haarp** [hexchat/hexchat#1711] opened 2016-05-12 18:07 UTC
The @ (at) character seems to break in Extra words to highlight. Attempting to add a phrase such as "@all" to it will result in no highlights when it is used by someone.

**Comment by Arnavion** [comment] 2016-05-12 18:31
Please search for existing issues before opening new ones.

Duplicate of #572

**Closed by Arnavion** 2016-05-12 18:31 UTC
