### ISSUE TITLE
When first connecting to servers, it should not change active window when a new connection is made. It's pretty annoynig to be in the middle of typing something out and then to be swiftly moved into another active server. Just leave the active tab on whatever you;re already on, what possib le benefit could there be for switching auto?

### ISSUE THREAD

**Issue by digitalnomad91** [hexchat/hexchat#2148] opened 2018-03-18 17:22 UTC
Thoughts? I can make a gif to illustrate what I mean if you guys don't get it.

**Comment by TingPing** [comment] 2018-03-19 03:48
I think I'll just lump this in as a Duplicate of #1676

You can disable focusing in *Preferences > Channel Switcher*

**Closed by TingPing** 2018-03-19 03:48 UTC
