### ISSUE TITLE
Indent nick names setting results in crash on mousover

### ISSUE THREAD

**Issue by Zagitta** [hexchat/hexchat#1441] opened 2015-08-04 02:33 UTC
Hello whenever I have the indent nick names setting enabled and move the mouse cursor into the chat area when the text in [this gist](https://gist.github.com/Zagitta/a138cdd24ffabe5ea22e) has been received Hexchat crashes on windows 8.1 and windows 10.

Here's an image of what it looks like right before crashing: 
![do2bpee](https://cloud.githubusercontent.com/assets/865977/9052010/4a65874a-3a62-11e5-82f7-37862121a731.png)

Is there any fix for this besides not using indent nick names?

**Comment by TingPing** [comment] 2015-08-04 13:32
Duplicate of #1389

**Closed by TingPing** 2015-08-04 13:32 UTC
