### ISSUE TITLE
Windows installer does not check privileges

### ISSUE THREAD

**Issue by mvhconsult** [hexchat/hexchat#2089] opened 2017-11-07 09:29 UTC
As said, the installer does not check or advertise that it needs rights to write to /program files. This causes an install failure when not enough privileges are available.

**Comment by learn-more** [comment] 2017-11-14 19:25
I'm not sure what you are doing, but the setup elevates correctly here.

**Comment by TingPing** [comment] 2017-11-14 20:01
Duplicate of #1735 ?

**Comment by mvhconsult** [comment] 2017-11-15 07:37
Seems like dupe of #1735 
I am running under limited user abilities. Running installer without explicit 'run as administrator' does not generate the request for admin access. 
Win10, 64, 1709

**Closed** 2017-11-15 17:48 UTC
Labels: duplicate
