### ISSUE TITLE
Ctrl+z doesn't work in input box

### ISSUE THREAD

**Issue by waqasilyas** [hexchat/hexchat#1449] opened 2015-08-11 18:52 UTC
At least one level of undo/redo is available by default on native text boxes (at least on Windows) and it is very common to use it to fix a tying mistake in the last word. Most of all unintended deletion can be reversed by a single level of undo very easily.

**Comment by TingPing** [comment] 2015-08-11 19:06
duplicate of #517

**Closed by TingPing** 2015-08-11 19:06 UTC
