### ISSUE TITLE
Hexchat will not reconnect if proxy is briefly unreachable

### ISSUE THREAD

**Issue by badon** [hexchat/hexchat#1212] opened 2014-11-21 01:16 UTC
When connecting to an IRC server via a proxy, Hexchat can be configured to auto-reconnect if the connection to the IRC server is lost. However, if the connection to the proxy is lost, Hexchat will not attempt to auto-reconnect. See also:

https://github.com/hexchat/hexchat/issues/475

**Comment by Arnavion** [comment] 2015-01-15 03:54
Duplicate of #849

This would be fixed by #600 (if ever).

**Closed by Arnavion** 2015-01-15 03:54 UTC
Labels: duplicate
