### ISSUE TITLE
See timestamp on hover feature.

### ISSUE THREAD

**Issue by madprops** [hexchat/hexchat#1629] opened 2016-03-11 20:07 UTC
I don't use the timestamps because I don't have much space and I prefer it that way, but sometimes I do want to know the date of a message. It would be nice if something like seeing a tooltip with the timestamp when hovering the nickname can be activated, that way I can keep timestamps off and check easily the date of a message.

**Comment by Arnavion** [comment] 2016-03-11 20:21
Please search for existing issues before opening a new one.

Duplicate of #1345

**Closed by Arnavion** 2016-03-11 20:21 UTC
