### ISSUE TITLE
Fatal Python error

### ISSUE THREAD

**Issue by 0pLuS0** [hexchat/hexchat#2340] opened 2019-05-18 03:13 UTC
Hi,

Running Slackware 14.1 x86, I compiled Hexchat 2.4.12 against Python 3.7.2.

When I close Hexchat I get this message back at the terminal;

Fatal Python error: PyInterpreterState_Delete: remaining subinterpreters

I see that there have been some issues reported about this in the past.

Any fix I can do on my end, or any fixes coming for hexchat?

Thanks

**Comment by TingPing** [comment] 2019-05-18 21:38
Duplicate of #2237

**Closed by TingPing** 2019-05-18 21:38 UTC
