### ISSUE TITLE
Unable to horizontally shrink window when search is active

### ISSUE THREAD

**Issue by shentino** [hexchat/hexchat#2287] opened 2018-12-15 14:00 UTC
When I type "ctrl-f" to search for a keyword, it forcibly extends the window's width, and no matter how hard I try it won't shrink past a certain minimum.  Even when the text I'm searching for is short.

Version 2.12.4, xfce desktop, Gentoo distro, kernel 4.19.9

**Comment by TingPing** [comment] 2018-12-23 22:55
Duplicate of #1030

**Closed by TingPing** 2018-12-23 22:55 UTC
