### ISSUE TITLE
DCC does not work with IPv6

### ISSUE THREAD

**Issue by marek22k** [hexchat/hexchat#2764] opened 2023-02-16 15:32 UTC
Hello,

I have sent the following request to HexChat:
```
DCC CHAT chat 2a02:180:6:1::1f24 2000
```
HexChat has tried to reach the IPv4 address `0.0.0.2`.

If I send the IPv6 with brackets, it shows `Received a malformed DCC request`.

I based this on the spec at https://modern.ircdocs.horse/dcc.html.

**Comment by TingPing** [comment] 2023-02-16 18:02
Duplicate of #1086

**Closed by TingPing** 2023-02-16 18:02 UTC
