### ISSUE TITLE
Allow configuration of ctrl+w keyboard shortcut (close channel)

### ISSUE THREAD

**Issue by JakobOvrum** [hexchat/hexchat#397] opened 2013-02-04 17:40 UTC
This can be quite annoying as browsers often use the same shortcut to close tabs.

After a short search I wasn't able to find the relevant source, hence this report. I wouldn't mind doing this myself if I was more familiar with the code.

**Comment by aoloe** [comment] 2016-06-18 16:47
sorry, i don't really see the interest of being able to create an empty channel with ctrl-n and closing the current channel with ctrl-w.

the context menu in the channel list and `/close` are imo more than good enough.
(the first one for those who join channels with the mouse, the second one for those who know about the irc command like `/join`: seriously: i can type faster `/join?  than i can press ctrl-w!).

i would suggest to simply remove both shortcuts (and, once you have gtk-3 you can let people who want the two shortcuts add them...)

adding a confirmation dialog might help... but i'm not sure that it's really needed.

**Comment by strycore** [comment] 2016-07-29 00:25
I have a patch to disable some keyboard shortcuts for those who want to compile hexchat without those enabled: https://github.com/strycore/buildscripts/blob/master/hexchat/disable-shortcuts.patch

**Comment by larsks** [comment] 2017-01-26 03:37
I came here to file an RFE for this, but I see everyone already beat me to it.

I'm constantly switching between terminals and hexchat and I type C-w for "backspace word" and then find myself trying to figure out which channel I just closed.  I'll try building a package with the patches from @strycore.

**Comment by aoloe** [comment] 2017-01-26 08:48
@strycore i'm not sure that disabling ctrl-q is a good idea (for sure, i can live with it!)... but disabling by default ctrl-n and ctrl-w seems the way to go...
would you mind making a pull request with that tiny patch so we can see what the developers think about it?

**Comment by TingPing** [comment] 2017-01-26 08:53
@aoloe See https://github.com/hexchat/hexchat/issues/397#issuecomment-20154069 for the problem with that.

**Comment by strycore** [comment] 2017-01-26 08:54
@aoloe I personally don't like Ctrl+q (I have a dedicated extension in Firefox to disable it) but people who are less clumsy than me might sometimes use that shortcut intentionally (unlike me).
I seem to remember that @TingPing didn't want to disable those shortcut and since he's one of the only contributors for one of my projects then I don't want to do anything that might annoy him XD

**Comment by aoloe** [comment] 2017-01-26 09:46
@TingPing , i agree that ctrl-w and ctr-n are common shortcuts.

but,  personally, i would never expect ctrl-w to quit a channel or ctrl-n to create a new empty channel.
i use both shortcuts very often (all the time) in document and window/tab oriented applications. but i never bothered to try them in an irc client. the context does not suggest me that i could try them.

also, as stated above, i have the feeling that hexchat already provides a simple textual way of closing (/close) and of adding a channel (/join).

i would normally not bother about useless shortcuts, but in this case it seems that i'm not alone in seeing nasty results related to them.

i'm now used to the issue and keep an eye on it (this means: ctrl-w and nothing happens? my eyes wander to the hexchat window and start wondering which channel has been closed...).
but i feel it as an unnecessary source of stress.

since you're not contributing to any of my projects ( :-) ) i dare to recommend you to apply strycore's patch... with or without the ctrl-q part, as you prefer.

**Comment by larsks** [comment] 2017-01-26 16:27
I've made some Fedora (25/26) packages available at https://copr.fedorainfracloud.org/coprs/larsks/hexchat/ with these patches applied.

**Closed** 2017-02-27 09:23 UTC
Labels: enhancement

**Comment by aoloe** [comment] 2017-02-27 10:57
nice, thanks!

**Comment by plehegar** [comment] 2018-04-10 13:34
For others who, like me, got the hexchat ctrl+w hard wired into their head: it can easily be added back by adding a "run command" with Data1 "/close" in the settings/keyboard shortcuts.

**Comment by stefanct** [comment] 2018-07-26 17:16
This led to a regression. Making things configurable is great (I have contributed such changes to some projects myself) - changing defaults that are standard in Unix applications since decades and in hexchat longer than it even exists... is not at all. Please add the defaults back.

**Comment by TingPing** [comment] 2018-11-24 22:31
@StephenLynx 	Settings > Keyboard Shortcuts > ctrl+w > run command /close

**Comment by shawnl** [comment] 2019-03-28 20:54
dvorak users should make the `ctrl` level use the QWERTY layout, so that all these types of commands are in the same place as usual, and where they were when they were designed.

**Comment by TingPing** [comment] 2019-03-28 21:05
@shawnl Set it to whatever you want, don't bump old bugs.
