### ISSUE TITLE
31 Character Limit for Proxy Authentication Password

### ISSUE THREAD

**Issue by Test45125** [hexchat/hexchat#1968] opened 2017-03-10 04:40 UTC
This has been this way since 2.10 at least. Using 2.12.4 x64, still has a 31 character limit.
Trying to modify the config file itself does not help bypass this limit.

Any way to increase the limit for more secure and longer passwords?

**Comment by TingPing** [comment] 2017-03-10 05:05
Duplicate of #1296

**Closed by TingPing** 2017-03-10 05:05 UTC
