### ISSUE TITLE
Hexchat crashes on Windows 10 with Python Plugin

### ISSUE THREAD

**Issue by nobodypb** [hexchat/hexchat#1594] opened 2016-01-27 13:55 UTC
Everytime I connect to a server hexchat crashes while loading the python plugin.
After I deleted hcpython2.dll hexchat works just fine.

**Comment by hdf** [comment] 2016-02-02 15:31
Just had the same problem on Windows 7. Solved it, by using [innounp](http://sourceforge.net/projects/innounp/files/innounp/) to extract "hcpython2.dll" from the 32 bit version of hexchat's installer, and using that. I'm on 64 bit windows, using 64 bit hexchat, and have both 32 and 64 bit python installed, but only the 32 bit one is in the path to avoid conflicts. (That one is the more commonly supported.) My guess is that the 64 bit "hcpython2.dll" tried to use 32 bit python, as that is the one it found in the path, and hence the crash. It seems, that the 64 bit version of hexchat can use the 32 bit version of "hcpython2.dll". (At least doesn't crash when loading it.) It is also possible, that the 64 bit version of "hcpython2.dll" is broken.

**Comment by TingPing** [comment] 2016-02-02 19:10
@hdf A 64bit application can't load a 32bit library so I have no clue what you are rambling about.

**Comment by hdf** [comment] 2016-02-02 20:33
Yes, it crashes, when you try to connect. Just checked, my bad, it really does not load the 32 bit "hcpython2.dll". So it works, because it is the same as if it was not even there. How does "hcpython2.dll" try to find where python is installed? That's where the problem seems to be. Just looking in path might not be a good idea, as it might find a different architecture, than the one it needs.

**Comment by TingPing** [comment] 2016-02-02 20:42
Python installs the dll's into either System32 or SysWow64 meaning it would not be in a shared path for the wrong bitness application. How the libraries are looked up and loaded is probably a question for Microsoft though.

**Comment by TingPing** [comment] 2016-02-02 20:44
And also connecting to a server is unrelated to loading the python dll, so I don't know whats going on there.

**Comment by Arnavion** [comment] 2016-02-02 20:46
>How the libraries are looked up and loaded is probably a question for Microsoft though.

I've confirmed that loading the wrong bitness is not possible and won't crash - LoadLibrary will return an error that it's a bad format and this propagates correctly all the way through HC and HC prints the same.

>And also connecting to a server is unrelated to loading the python dll, so I don't know whats going on there.

"Connecting to a server" probably refers to the firstrun connect-to-network dialog. Plugins are loaded after it.

**Comment by Arnavion** [comment] 2016-02-02 20:47
As for the crash it's likely the same one I'm seeing - an `exit(1)` in PyInitializeEx when it fails to load the `site` module for whatever reason.

**Comment by Arnavion** [comment] 2016-02-02 23:19
So there's two Python bugs here:

1. 2.7 is supposed to look up the path where modules are installed from a registry key placed by the installer, except the 32-bit version of 2.7.11 looks in the wrong registry path (`HKLM\Software\Python\PythonCore\2.7-32\PythonPath` instead of `HKLM\Software\Python\PythonCore\2.7\PythonPath`) That's bug https://bugs.python.org/issue25824

1. In 2.7 they added an exit(1) call if it fails to find the `site` module because of course libraries should call exit() it's not like C functions can return error codes or anything what kind of arcane shit is that. So because of the above it can't find the module, so it exits.

So either use Python 3, or downgrade Python 2 to 2.7.10 or something.

**Comment by TingPing** [comment] 2016-02-03 00:35
So at least partially duplicate of #1568 (OP never mentioned he was on 2.7.11)

**Closed** 2016-02-03 00:40 UTC
Labels: duplicate

**Comment by nobodypb** [comment] 2016-02-04 13:16
Sorry for providing that little information. I'm on 64bit and using Python 2.7.11 32bit. I didn't see #1568 but the solution fixed it for me aswell, so thanks for the support guys.
