### ISSUE TITLE
Crashes when Win8.1 wake up (from suspend mode)

### ISSUE THREAD

**Issue by mzalazar** [hexchat/hexchat#1564] opened 2015-12-11 08:35 UTC
I have win8.1 and when i push power button (it was in stand by mode) and my desktop is restored, then a window tell me that this program stops functioning :(

**Comment by TingPing** [comment] 2015-12-11 14:18
Duplicate of #600

**Closed by TingPing** 2015-12-11 14:18 UTC

**Comment by paladox** [comment] 2015-12-17 00:25
I noticed that under the chat bar that is on the right the users that are avalible to chat there is a green bar when you reconnect or lose connection that will load until it is fully green then it crashes.
