### ISSUE TITLE
Find bar crashes Hexchat

### ISSUE THREAD

**Issue by Ketsuban** [hexchat/hexchat#1541] opened 2015-11-08 21:03 UTC
I am using Hexchat 2.10.2 from the Ubuntu 15.10 repositories. I tried to find a relevant issue from someone with a more recent build and found nothing.

Steps to reproduce
-----------------------
1. Open Hexchat.
2. Join a few high-traffic channels across multiple different servers. (I don't know if the specific servers and channels I connect to are relevant, but a fresh Hexchat window with no active connections did not crash.)
3. Time passes. You are likely to be eaten by a grue.
4. Open the find bar with Ctrl-F.
5. Close the find bar by clicking the leftmost button.

Expected result
-------------------
The find bar closes. Hexchat continues being an IRC client.

Actual result
---------------
Hexchat crashes a couple of seconds after clicking the button. The UI may or may not freeze up beforehand—I *think* this depends on the amount of text the window the find bar is opened in contains.

**Comment by TingPing** [comment] 2015-11-08 21:30
Duplicate of #1280, but i think this has been fixed in https://github.com/hexchat/hexchat/commit/c8539b93fe65977ee507b473e9dd62a1cc7bec53 so if you could try building from git that would be great.

**Closed by TingPing** 2015-11-08 21:30 UTC

**Comment by hub2git** [comment] 2017-03-15 03:30
Crashes for me,too. Using Linux Mint cinnamon 18.1. hexchat is from official (I.e, Mint) repository. Updated to whatever the latest version in the repository is. Please let me know how to give you the info you need to figure out the problem.

**Comment by hub2git** [comment] 2017-03-15 03:33
@TingPing has not the c8539b9 commit you refer to been merged into Mint repo? I would think that one entire year would be plenty of time to get the fix in.

**Comment by TingPing** [comment] 2017-03-15 03:38
@hub2git That isn't how mint (Ubuntu LTS) works, you get one major update every 2 years so the next update you get is in 2018 and their current version is from 2014.
