### ISSUE TITLE
HexChat Bug causes Program Crash.

### ISSUE THREAD

**Issue by PinkieShyDash** [hexchat/hexchat#1349] opened 2015-04-12 02:40 UTC
Hopefully this video will say it all about how to do the bug and showing Hexchat crashing..
https://www.youtube.com/watch?v=3xAwDvjnJ7w&feature=youtu.be

**Comment by Arnavion** [comment] 2015-04-12 02:54
Duplicate of #600

**Closed by Arnavion** 2015-04-12 02:54 UTC
