### ISSUE TITLE
Rplacing CRLF with LF

### ISSUE THREAD

**Issue by miroklarin** [hexchat/hexchat#2560] opened 2021-04-10 16:53 UTC
As an user I would like to reuse config files between Linux and Windows system to maintain same list of subscribed channels
When Windows client is open, it replaces `LF` to `CRLF` in config files
When Linux client use same files later, auto connect starts looping as channel auto join fails
The reason is `CRLF` character after channel name in config files
Replacing `CRLF` with `LF` for all channels fixes the issue

**Comment by TingPing** [comment] 2021-05-24 01:18
Duplicate of #2234

**Closed by TingPing** 2021-05-24 01:18 UTC
