### ISSUE TITLE
Crash on Win64

### ISSUE THREAD

**Issue by decafbad** [hexchat/hexchat#495] opened 2013-04-02 19:50 UTC
Hexchat crashed after a network connection failure. Unfortunately I know nothing about coding on Windows. All I've seen is when it crashed Visual Studio showed up itself to debug. So I took a dump. I hope this file contains some useful information. 

http://dl.dropbox.com/u/24346270/hexchat.dmp.7z

**Comment by Arnavion** [comment] 2015-02-27 21:33
Probably duplicate of #600

**Closed by Arnavion** 2015-02-27 21:33 UTC
Labels: bug
