### ISSUE TITLE
Segmentation Fault when right clicking misspelled words.

### ISSUE THREAD

**Issue by DinsFire64** [hexchat/hexchat#2101] opened 2017-12-11 04:59 UTC
Went to go fix a misspelled word and got a segmentation fault. Running the latest version of Arch.

Here's a backtrace, let me know what else I can grab to figure out why this is happening.

```
(gdb) run
Starting program: /usr/bin/hexchat 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffe6c43700 (LWP 15425)]
[New Thread 0x7fffe6442700 (LWP 15426)]
[New Thread 0x7fffdd666700 (LWP 15429)]

Thread 1 "hexchat" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) backtrace
#0  0x0000000000000000 in  ()
#1  0x00005555555b2035 in  ()
#2  0x00005555555b4ff9 in  ()
#3  0x00007ffff5b4d6f5 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#4  0x00007ffff5b610b0 in  () at /usr/lib/libgobject-2.0.so.0
#5  0x00007ffff5b65696 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#6  0x00007ffff5b66920 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#7  0x00007ffff7854c61 in  () at /usr/lib/libgtk-x11-2.0.so.0
#8  0x00007ffff79f8092 in  () at /usr/lib/libgtk-x11-2.0.so.0
#9  0x00007ffff5b4d6f5 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#10 0x00007ffff5b610b0 in  () at /usr/lib/libgobject-2.0.so.0
#11 0x00007ffff5b65696 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#12 0x00007ffff5b6662c in g_signal_emit_by_name () at /usr/lib/libgobject-2.0.so.0
#13 0x00007ffff7929cb3 in  () at /usr/lib/libgtk-x11-2.0.so.0
#14 0x00007ffff792d7b9 in  () at /usr/lib/libgtk-x11-2.0.so.0
#15 0x00007ffff78c87ac in  () at /usr/lib/libgtk-x11-2.0.so.0
#16 0x00007ffff5b4d6f5 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#17 0x00007ffff5b60ae2 in  () at /usr/lib/libgobject-2.0.so.0
#18 0x00007ffff5b64efe in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#19 0x00007ffff5b66920 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#20 0x00007ffff79e08cc in  () at /usr/lib/libgtk-x11-2.0.so.0
#21 0x00007ffff78c7503 in gtk_main_do_event () at /usr/lib/libgtk-x11-2.0.so.0
#22 0x00007ffff753e46c in  () at /usr/lib/libgdk-x11-2.0.so.0
#23 0x00007ffff587d270 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#24 0x00007ffff587ef69 in  () at /usr/lib/libglib-2.0.so.0
#25 0x00007ffff587ff42 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#26 0x00007ffff78c63a7 in gtk_main () at /usr/lib/libgtk-x11-2.0.so.0
#27 0x000055555558d5fa in fe_main ()
#28 0x0000555555581319 in main 
```

**Comment by Arnavion** [comment] 2017-12-11 17:10
Duplicate of #2099

**Closed by Arnavion** 2017-12-11 17:10 UTC

**Comment by DinsFire64** [comment] 2017-12-11 17:13
Perfect thanks.
