### ISSUE TITLE
Changing the input icon of ' ?

### ISSUE THREAD

**Issue by TBloemink** [hexchat/hexchat#1960] opened 2017-02-28 00:26 UTC
This is more necessarily a question than an issue but is there a way to change the way the apostrophe is inserted? Hitting the ' button and pressing space like I always input the icon puts in a ´ instead of a regular apostrophe. Is this configurable or changable in hexchat?

**Comment by TingPing** [comment] 2017-02-28 01:12
Duplicate of #304

**Closed by TingPing** 2017-02-28 01:12 UTC
