### ISSUE TITLE
debian 10 tray

### ISSUE THREAD

**Issue by sacredland** [hexchat/hexchat#2429] opened 2020-01-18 01:10 UTC
Using debian 10, Kstatusnotifieritem/appindicator is on, using Gnome 3.30.2, hexchat 2.14.3 and I've lost the tray indicator (then cannot minimize on it). nothing appear into setting -> preference -> alert regarding the minimizing option. on debian 9 with hexchat 2.14.2 i had it

**Comment by sacredland** [comment] 2020-01-18 01:11
> Using debian 10, Kstatusnotifieritem/appindicator is on, using Gnome 3.30.2, hexchat 2.14.3 and I've lost the tray indicator (then cannot minimize on it). nothing appear into setting -> preference -> alert regarding the minimizing option. on debian 9 with hexchat 2.14.2 i had it

and 
[20:01:40]  gui_tray set to: 1 (was: 1)
[20:02:03]  gui_tray_minimize............: ON

**Comment by TingPing** [comment] 2020-01-18 01:34
Duplicate of #1235

**Closed by TingPing** 2020-01-18 01:34 UTC
