### ISSUE TITLE
Feature request: scroll up from bottom

### ISSUE THREAD

**Issue by internectual** [hexchat/hexchat#1695] opened 2016-05-03 21:34 UTC
The default behavior of HexChat is to start from the top of a window and add news lines until the bottom limit is reached and then scroll all text up.

My request is to have an option to start new text at the bottom of the window and scroll up as new lines are added. Text in new windows would show immediately above the input box, increasing readability for new messages when HexChat's window is behind another program, but not completely obstructed.

**Comment by TingPing** [comment] 2016-05-04 00:18
Duplicate of #903

**Closed by TingPing** 2016-05-04 00:18 UTC
