### ISSUE TITLE
Duplicate tray icons created

### ISSUE THREAD

**Issue by ElPumpo** [hexchat/hexchat#1423] opened 2015-07-16 18:46 UTC
![untitled](https://cloud.githubusercontent.com/assets/1096010/8735865/f536e680-2bc8-11e5-9f69-74ac1ae4ee43.png)
![untitled](http://i.imgur.com/U5SWacN.png)
These Icons appears randomly on my tray bar after hexchat being on for a while.
Pressing on any of the tray Icons crashes hexchat.

Technical info:
- using a 1440p monitor (DELL U2515H)
- connected via display port 1.2
- running windows 10 insider

**Comment by ElPumpo** [comment] 2015-07-17 22:21
http://i.imgur.com/U5SWacN.png

Even worse now

**Comment by Cisien** [comment] 2015-08-29 01:34
This happens for me whenever the resolution changes. Clicking on one of these icons will cause hexchat to crash.

**Comment by tomek** [comment] 2015-09-02 20:45
@ElPumpo @Cisien could you check this build https://dl.hexchat.net/hexchat/testing/tomek/tray-issue/ and report if it still happens for you?

**Comment by ElPumpo** [comment] 2015-09-03 18:13
@tomek yes, the issue seems to be solved with the build you linked, i'll keep you updated.

BTW: http://i.imgur.com/ipOAjHb.png
HexChat detects win10 as win8.1

**Comment by prenetic** [comment] 2015-09-10 22:13
Had this same issue with Windows 10 x64, where clicking any of the icons after they were duplicated would result in an immediate crash. The build suggested by @tomek seems to have resolved the issue.

**Comment by ElPumpo** [comment] 2015-09-11 17:10
I don't have a 4k monitor, got a 1440p one.

**Comment by prenetic** [comment] 2015-09-21 17:44
Update: this still seems to be an issue (under the test build) when accessing the workstation via remote desktop. Clicking on the systray icon during or after a remote desktop session will cause Hexchat to crash.

**Comment by tomek** [comment] 2015-09-21 17:56
@prenetic I just checked it and hexchat didn't crash for me - maybe it's because I didn't have this issue. btw hexchat had few issues when using it over RDP - maybe that's why it crashes for you.

**Comment by prenetic** [comment] 2015-09-21 17:59
While I agree that it's no longer crashing while physically at the machine, I'm still running into crashing over RDP when interacting with the systray icon. I am now starting to wonder if this is related to the display scaling Windows 10 does over RDP (4K at physical workstation, 1080p over RDP). Perhaps this particular issue may be more closely related to #1477.

**Comment by pureby** [comment] 2015-10-26 11:20
@tomek I have exact same issue and the build you have provided above (https://dl.hexchat.net/hexchat/testing/tomek/tray-issue/) __does not solve__ the issue for me.

What happens in my case is this:
— using a laptop running Windows 10 (64-bit)
— I have _'disabled display scaling on high DPI' setting_ for HexChat (it looks blurry otherwice) 
— a second screen (with a different resolution) is connected to my laptop 24/7, however it is switched off most of the time (I only power it on when I really need to)
— my laptop is set up to ignore closing the lid (laptop does _not_ go to sleep when closing the lid)
— whenever I close the lid of my laptop (every night before I go to sleep) Windows detects that the lid is closed and automatically switches the image to the second monitor, even though the second monitor is powered off
— this moment of resolution / screen changing is exactly when HexChat creates a new icon in sys tray
— HexChat continues to run properly, but crashes the moment one of the tray icons is clicked

Hope this helps! Thanks in advance!

**Comment by justapoorboy** [comment] 2016-04-28 22:08
I'm still having this issue on version 2.12.0 (Windows 10)
Tried the test build linked above beforehand and still experienced the issue.

I frequently switch between displays. My main computer monitor is a 1440 monitor, but I'm running it at 1920x1080. My secondary 'monitor' is a Samsung TV, which has DPI scaling(?) enabled because I have bad eyes. I've tried disabling DPI scaling in the compatibility tab for my HexChat shortcut.

**Comment by ElPumpo** [comment] 2016-04-29 06:34
Yeah, the issue came back

**Comment by wbierman** [comment] 2016-05-28 06:45
I am also experiencing this issue.  I am running at 4K resolution with 1.0 scaling.

**Comment by TingPing** [comment] 2016-05-28 17:01
Yes this is clearly related to hidpi support changes in Win10 so we just need somebody familiar with the windows changes to dig into whatever gtk is doing for the tray icon.

**Comment by wbierman** [comment] 2016-05-31 20:58
What do you mean when you say "the windows changes"?  Are you referring to a recent change to Windows?  A recent change to hexchat specific to Windows?  If the later, can you show some recent related commit(s)?

**Comment by TingPing** [comment] 2016-05-31 20:59
A change between windows 8.1 and windows 10.

**Comment by 8bitbubsy** [comment] 2016-07-05 17:30
With the latest version of hexchat, every time I turn off and on my Dell U2515H monitor (2K resolution), I get the cloned icons (+ crash if I click on them)... This is just unbearable! So every time I wake up and turn on the monitor, I need to reopen hexchat...

**Comment by tomek** [comment] 2016-07-05 18:36
@8bitbubsy could you try test build from here: https://dl.hexchat.net/hexchat/testing/ .Like I wrote before I never encountered that issue - but I've only two 1080p monitors so I can't really tell if it is related to resolution.

**Comment by 8bitbubsy** [comment] 2016-07-05 18:40
@tomek Sorry, it changed nothing. :(

**Comment by ElPumpo** [comment] 2016-07-05 19:11
Really? Using a DELL U2515H monitor myself, connected using display port. We need to donate this dude some hardware.

**Comment by TingPing** [comment] 2016-07-05 19:35
The main Windows developer is @Arnavion but they do not use Windows 10 (and probably doesn't have a hidpi monitor) so it would largely be up to them to care to reproduce the problem. If I had such a monitor I do have a Windows 10 installation but myself am largely unfamiliar with win32.

**Comment by wbierman** [comment] 2016-07-05 19:42
I use 2.12.1 on Windows 10, I am using two DisplayPort 1.2-connected monitors.  This no longer happens to me.

**Comment by ElPumpo** [comment] 2016-07-05 19:53
@TingPing @Arnavion what is it with people and not "caring"? Not caring means that people will use another project instead, which I already have done (not to hate or anything, I love open source projects).

**Comment by TingPing** [comment] 2016-07-05 20:02
Well its a hobby project so somebody has to do the work.. I certainly can't drop $500 on a new monitor to fix a bug.

**Comment by Arnavion** [comment] 2016-07-06 18:54
Someone who has W10, a 4k monitor connected via dp and scaling set to 150% tells me they disabled scaling in HC (and increased the font size to compensate) because HC is "a blurry mess" otherwise. They also do not observe crashes when they turn off their monitors, but they also avoid turning them off in the first place, so take that as you wish.

**Comment by 8bitbubsy** [comment] 2016-07-06 18:57
It didn't crash for me when I turned off my monitor and then back on, but the taskbar icon got cloned (this exact bug report), and clicking on any of the fake ones would result in HexChat crashing. As said, when I used HDMI instead of DisplayPort, the problem was gone. Protocol differences I guess. Windows is doing something stupid when the (only) DisplayPort device is "disconnected".

**Comment by ElPumpo** [comment] 2016-07-06 19:11
You're only starting to pay attention 1 year later? @Arnavion did you even read the report at the top?

**Comment by Arnavion** [comment] 2016-07-06 19:16
I figured it was obvious that I was relaying information from someone else and implied nothing less and nothing more than what they said. I can't exactly force them to turn off their monitors and observe exactly what happens when they explicitly said they don't want to do that.

**Comment by ElPumpo** [comment] 2016-07-06 20:18
Who told you that it happens when you turn the monitor off and on? It happens when you run the application minimized.

**Comment by Arnavion** [comment] 2016-07-06 21:22
https://github.com/hexchat/hexchat/issues/1423#issuecomment-151104283

**Comment by ElPumpo** [comment] 2016-07-07 11:04
Well, maybe that too but primarly when you're switching resolutions by for example start a fullscreen game.
Whatever, I'm not going to keep posting comments now as I see no idea of doing so.

**Comment by tomek** [comment] 2016-07-07 19:26
I uploaded new test build (e647cd0 - available here: https://dl.hexchat.net/hexchat/testing/) which should fix issue with duplicate icons in tray - I wasn't able to reproduce it here (I found a way to reproduce it just by changing the dpi scaling in windows settings - without the need for hidpi monitor).

**Comment by tostercx** [comment] 2016-07-09 20:38
Fixed it form me! Thank you, this had been bugging me for so long :)

**Comment by cheatfreak47** [comment] 2016-07-11 03:44
@tomek just tried it myself and it fixed the problem for me as well, seems you squashed the bug good.

**Comment by 8bitbubsy** [comment] 2016-07-11 10:24
Yup, bug is gone! Anyways guys, it's not _only_ DPI related, because my zoom is always 100% (no upscaling) in Windows.

**Comment by Arnavion** [comment] 2016-07-11 15:05
The above commit is merged into master. I'm leaving this open until some of the initial posters confirm, since it seems everyone had different triggers for the bug.

**Comment by wbierman** [comment] 2016-07-12 05:54
I was able to reproduce the issue on 2.12.1 by adjusting my scaling (4K resolution using DisplayPort 1.2 on Windows 10).  The binary shared by @tomek appears to solve the problem for me.  Thanks!

**Comment by db0451** [comment] 2016-07-19 06:57
@TingPing "Upstream is likely of no help for these issues also sadly." C'mon. Upstream has to know about something before they can help. Assuming they won't care is self-defeating. Once made aware of the issue, they were happy to accept a patch, even backporting it to the ancient v2 branch too. Their Win32 devs may be fewer, but they're dedicated.

**Comment by TingPing** [comment] 2016-07-19 09:04
@db0451 I admit I am a little unfair but this widget is deprecated upstream and the win32 maintainer does focus on Gtk3 and he had no Win10 setup. He accepted this patch purely because "It looks fine and the widget is deprecated anyway".

**Closed** 2016-11-04 12:24 UTC
Labels: bug, win32
