### ISSUE TITLE
Spawns new system tray icon

### ISSUE THREAD

**Issue by Beat-Nick** [hexchat/hexchat#1609] opened 2016-02-11 18:27 UTC
Using version 2.10.2 of client on windows 10. When running for a while it seems to spawn [additional system tray icons](http://imgur.com/3xbvxrH). No new process is actually started, it just fills up my system tray. Clicking on the 'incorrect' icon will crash the program.

I am running 21:9 resolution with an upscaled windows interface to 1.25 is the only thing 'unique' compared to my other machines where hex runs fine.

**Comment by Arnavion** [comment] 2016-02-11 19:27
Duplicate of #1423

**Closed by Arnavion** 2016-02-11 19:27 UTC
