### ISSUE TITLE
Official Mac OS releases

### ISSUE THREAD

**Issue by martell** [hexchat/hexchat#1923] opened 2017-01-03 20:19 UTC
Hey, 

I was installing OSX builds from https://dl.hexchat.net/hexchat/osx/
The last of which was 2.10.2 and we are now on 2.12.4 so thats very far behind.

I know we can build it via homebrew and install it but is there a reason why the app packages are not made available anymore?
I prefer that method of install because it is easier to have it in Applications without any icon issues and mapped to the dock.
I can do the builds for the release if the team does not want to do this anymore
Just looking for some answers

Best,
Martell

**Comment by TingPing** [comment] 2017-01-03 20:20
Duplicate of #1858

**Closed by TingPing** 2017-01-03 20:20 UTC

**Comment by martell** [comment] 2017-01-03 20:26
Ohh sorry I didn't see that when I searched the issues for Mac.
Thanks for clearing that up @TingPing .
Sorry for the noise

**Comment by TingPing** [comment] 2017-01-03 20:45
@martell There should be plenty of information on building your own bundles and feel free to host them for others but I don't think they will be "official".

**Comment by philicious** [comment] 2017-01-12 14:14
@martell I was also looking for a Mac version and did build a HexChat.app bundle , grab it here https://github.com/philicious/hexchat/releases/tag/2.12.4

**Comment by ekhaydarov** [comment] 2018-07-20 09:35
doesnt work on the latest highsierra :(

**Comment by philicious** [comment] 2018-07-20 14:09
@ekhaydarov see https://github.com/hexchat/hexchat/issues/1931#issuecomment-390948491 aswell as https://github.com/hexchat/hexchat/issues/2173 on how to build for HighSierra.

**Comment by CyberManifest** [comment] 2018-07-20 19:48
@philicious could you update your HexHat.app bundle binary to use the latest HexChat 2.14.1 ?

**Comment by zeamp** [comment] 2023-09-05 15:16
Any progress on HexChat for macOS Sonoma? Older builds of HexChat crash upon use, or display for a second, or the text/DPI is blurry.
