### ISSUE TITLE
HexChat isn't starting normally

### ISSUE THREAD

**Issue by Gustavo6046** [hexchat/hexchat#1656] opened 2016-03-24 22:51 UTC
Starting some few hours ago I installed Python 2.7.11 and Python 3.5.1. I tried to run HexChat but it didn't run! It runs for a fraction of second only, showing a vanished window for few centiseconds sometimes. Then it closes by itself.

Sorry if this is a duplicate, I don't like the Search function because it never returns me the duplicate question when I enter related words in.

Windows 10 64-bit x64 OS.

**Comment by TingPing** [comment] 2016-03-24 23:00
Duplicate of #1568

**Closed by TingPing** 2016-03-24 23:00 UTC
