### ISSUE TITLE
Ctrl + Z on input texts

### ISSUE THREAD

**Issue by danielgiljara** [hexchat/hexchat#2756] opened 2023-01-17 15:35 UTC
Hello,

I would like to have Ctrl + Z on input texts.

**Comment by TingPing** [comment] 2023-01-17 18:10
You can use this script for now: https://github.com/TingPing/plugins/blob/master/HexChat/undo.lua

**Comment by TingPing** [comment] 2023-01-17 18:10
Duplicate of #517

**Closed by TingPing** 2023-01-17 18:10 UTC
