### ISSUE TITLE
"Log to disk" cannot be disabled for server tab

### ISSUE THREAD

**Issue by sagamusix** [hexchat/hexchat#1346] opened 2015-04-09 00:45 UTC
When trying to disable "log to disk" from the context menu of a server tab, the option is checked again on the next HexChat restart, so even if you don't want this stuff to be logged (but want channels and privmsgs to be logged), you will eventually get megabytes of useless log files containing MOTDs and other server stuff.

**Comment by sagamusix** [comment] 2015-04-09 01:17
Preferrably, disabling logging for the server tab would also stop logging those NetworkName-status.log files, not just NetworkName-NetworkName.log

**Comment by TingPing** [comment] 2015-04-09 02:00
Duplicate of #858

**Closed by TingPing** 2015-04-09 02:00 UTC
