### ISSUE TITLE
add a way to configure a proxy per  IRC network

### ISSUE THREAD

**Issue by bmintz** [hexchat/hexchat#2366] opened 2019-08-14 16:00 UTC
I have some networks configured to use Freenode over Tor. To connect to both of these, I have to disable my proxy in network settings, connect to the clearnet freenode network, then enable my proxy, then connect to the Tor freenode network. And if one of them gets disconnected I have to do that again. It would be great if there was a proxy configuration _per network_. Cheers.

**Comment by TingPing** [comment] 2019-08-15 03:53
Duplicate of #782

**Closed by TingPing** 2019-08-15 03:53 UTC
