### ISSUE TITLE
FiSHLiM keyx to exchange keys with another user

### ISSUE THREAD

**Issue by MrRH** [hexchat/hexchat#1083] opened 2014-08-05 21:43 UTC
The current FiSHLiM plugin does not support any key exchange between clients.
This is working in xchat old version but it is not compatible with hexchat.

When trying to do /keyx you get keyx :Unknown command
When another client tryes to do /keyx ,  you get this (random example taken from IRC):
DH1080_INIT_cbc hi4f7k4P3JF5v4k8jVcHs8WLfk8WKUWb6HDR+k0YKc7cZHp6zfAoM5EZi8dw0abpkq6keTame9S+aLk6tktqLtDSdWCBdKM0/C/w5PeAxXlNr6hORlG+jf/Uy7ICNxaXpxCvtTuORtcbmz4iQqAA3KLplaeA/t5hQOWCEHMvSfxLBvgqfMIHA

I believe that being able to do key exchange with other clients is essential part of fishlim encryption and whitout it is not compatible with other clients running different types of FiSHLiM plugins, also wraith botnet that uses random keys to encrypt the communication and only way to get the key is accepting the key from the client, in this case wraith bot.

**Comment by philicious** [comment] 2015-08-03 12:50
Here you go guys. My build https://mega.co.nz/#!PsphHY6A!kHcBtToVRrAoFJQcrG6gK5zvna8yTvRgElgYLeMIls8

until #1440 gets merged

**Comment by iyx** [comment] 2016-08-27 11:01
@philicious can you make x64 build too?

**Comment by philicious** [comment] 2016-08-27 11:15
@iyx ye, its already available. check the release page on my fork https://github.com/philicious/hexchat/releases . 

PS: most of the discussion happened in #1440 and maybe, if more people express interest there. we can finally convience HexChat guys to get Key-Exchange etc officially.

**Comment by Arnavion** [comment] 2016-08-27 17:10
>maybe, if more people express interest there. we can finally convience HexChat guys to get Key-Exchange etc officially.

You realize that the PR hasn't been merged because there's a ton of things you need to fix to make it better, not because "the HexChat guys" need convincing, yes?

**Comment by philicious** [comment] 2016-08-27 17:28
@Arnavion I would agree in general, but HexChat had the plugin in their repo already but missed the crucial part of KeyExchange. I know there are still some things that need to be modified to meet project standards. However I hope the original maintainer (HexChat) could do the rest to serve public interest. Otherwise this PR will never get merged and the plugin could be removed entirely.

With my additions its working fine btw and people are grabbing it from my fork instead of this repo. Which doesnt make much sense.

**Comment by TingPing** [comment] 2016-08-27 18:11
HexChat is not the original creator of the plugin that would be here: http://fishlim.kodafritt.se/

So that PR would be the first major feature additions by us to it.

> With my additions its working fine btw and people are grabbing it from my fork instead of this repo. 

The point isn't that it doesn't work the point is it isn't quite up to quality/standards to be merged yet.

**Comment by philicious** [comment] 2016-08-27 22:18
@TingPing ok, then I misinterpreted the situation. I thought Hexchat would be the maintainer by now as its in your master branch.
I didnt mean anything offensive. Its just that I dont have the time to make the remaining modifications to meet the requirements. However, another user contributed patches to my PR to address at least some of the "problems". 
And as I've seen many people expressing interest in the full-featured plugin, it would be awesome if one of HexChat core devs could bring it to a state where its mergable so people would get it shipped right away with HexChat.

**Comment by TingPing** [comment] 2016-08-28 22:39
@philicious I'll try to work on rewriting and merging it soon.

This issue is a duplicate of #653 anyway I'm not sure why this stayed open.

**Closed by TingPing** 2016-08-28 22:39 UTC
Labels: enhancement, plugin
