### ISSUE TITLE
Hexchat crashes when hovering the mouse over the main/content area

### ISSUE THREAD

**Issue by Hund** [hexchat/hexchat#1431] opened 2015-07-23 22:45 UTC
HexChat works just fine As long as I dont hover the mouse over the main/content area in lack of a better words.

Starting Hexchat via the terminal outputs only a single line when it crashes: "zsh: segmentation fault (core dumped)  hexchat".

I really dont know what to do? I cant seem to debug it anyway?

Im using Arch Linux with Hexchat version 2.10.2-3.

**Comment by TingPing** [comment] 2015-07-23 22:50
Duplicate of #1389

**Closed by TingPing** 2015-07-23 22:50 UTC
