### ISSUE TITLE
Typing an apostrophe(') results in an accent (´)

### ISSUE THREAD

**Issue by Czorio** [hexchat/hexchat#2030] opened 2017-08-04 14:43 UTC
Whenever I try to type the ' character it will result in a ´ instead. I have tried changing charsets, but anything else than utf-8 is not usable when considering other users. The same happens for the " character, which will turn into a ¨ instead.

Keyboard layout is US (International)
Hexchat version is 2.12.4 X64 (not portable)

This only happens in my Hexchat client, everything else works fine.

Image example:
![image](https://user-images.githubusercontent.com/8137653/28973417-6a0c1b9c-7933-11e7-9d74-47a77ab70faa.png)

Any help I can get with this would be nice.

**Comment by TingPing** [comment] 2017-08-04 15:01
Duplicate of #304

**Closed by TingPing** 2017-08-04 15:01 UTC
