### ISSUE TITLE
Mention Notifications show many minutes late

### ISSUE THREAD

**Issue by justarandomgeek** [hexchat/hexchat#1831] opened 2016-10-04 19:23 UTC
I'm running HexChat 2.12.1 on Win10 x64 Build 1607 (but it was happening occasionally in earlier builds also), and I often get the tray notification for a nick mention many minutes later than the actual mention. It's usually quick when I first start HexChat, but after a day or two they're delayed by 5-7 minutes!

Is there anything I can collect that might shed light on why this is happening?

**Comment by TingPing** [comment] 2016-10-04 19:58
Some Windows bug, if you google around various users with various applications have the same issue.

**Comment by Arnavion** [comment] 2016-10-04 20:05
Duplicate of #1419

**Closed by Arnavion** 2016-10-04 20:05 UTC
