### ISSUE TITLE
Please port the code to use getaddrinfo()

### ISSUE THREAD

**Issue by nemysis** [hexchat/hexchat#1687] opened 2016-04-18 14:05 UTC
In openSUSE I get this with build

```\n
[   97s] RPMLINT report:
[   97s] ===============
[   99s] hexchat.x86_64: I: binary-or-shlib-calls-gethostbyname /usr/bin/hexchat
[   99s] The binary calls gethostbyname(). Please port the code to use getaddrinfo()
```

**Comment by TingPing** [comment] 2016-04-18 14:21
Duplicate of #643

**Closed by TingPing** 2016-04-18 14:21 UTC
