### ISSUE TITLE
Segfault on spellcheck right-click menu

### ISSUE THREAD

**Issue by einstein95** [hexchat/hexchat#2099] opened 2017-11-30 07:20 UTC
Running
```
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
```
HexChat 2.12.4
OS: Linux 4.14.2-1.ARCH

When right-clicking a misspelt word in the input box, HexChat crashes with
```
(hexchat:20289): Gdk-CRITICAL **: _gdk_pixmap_new: assertion '(width != 0) && (height != 0)' failed
(hexchat:20289): Gdk-CRITICAL **: _gdk_pixmap_new: assertion '(width != 0) && (height != 0)' failed
(hexchat:20289): Gdk-CRITICAL **: _gdk_pixmap_new: assertion '(width != 0) && (height != 0)' failed
[1]    20289 segmentation fault (core dumped)  hexchat
```

**Comment by TingPing** [comment] 2017-11-30 20:32
Probably duplicate of #2095

**Comment by einstein95** [comment] 2017-12-01 10:37
Yup, downgrading enchant worked. Thanks for the heads up.

**Closed** 2017-12-01 10:37 UTC

**Comment by TingPing** [comment] 2017-12-01 19:44
Somebody should report this to Arch so they can backport that patch.
