### ISSUE TITLE
OS X El Capitan: Two apple menu symbols, second does nothing.

### ISSUE THREAD

**Issue by WillEccles** [hexchat/hexchat#1483] opened 2015-09-15 23:43 UTC
Note: this is untested on other versions of OSX (at least by me).

On the El Capitan (10.11) beta, there are two apple icons. Not sure about other versions, but this one has this issue. See attached image.
![screen shot 2015-09-15 at 7 39 02 pm](https://cloud.githubusercontent.com/assets/3360049/9892967/ea4f7b58-5be1-11e5-8563-b1a0b4c91156.png)

**Comment by TingPing** [comment] 2015-09-15 23:48
Duplicate of #994

**Closed by TingPing** 2015-09-15 23:48 UTC
