### ISSUE TITLE
Random Crashing, connection issues?

### ISSUE THREAD

**Issue by VasVadum** [hexchat/hexchat#1520] opened 2015-10-26 08:10 UTC
Hexchat appears to have no crash logging to tell you why it crashed.  I suggest that you add this feature so people can see why it crashed.  I'm getting fed up with all the bugs in HexChat so I'm going to post each one that I'm having in a separate issue and hope that they can be resolved.

This issue, it seems that HexChat turns white and says that it has stopped working, after a connection issue has just happened.  Way back, many months ago, it used to happen when my internet was a 2.4GHz microwave dish pointed at a tower 5 miles away with 4 miles of trees blocking the path causing 80-90% packetloss.  It kept trying to reconnect, and one of it's reconnect attempts, it would turn white and crash.

Now, I'm using a 4G LTE phone with an ADB Bridge tether app called Clockworkmod Tether, if I should disconnect my phone to go somewhere for a bit leaving the tether on my laptop running but "trying to reconnect" over and over leaving a dead wired connection open (with the yellow triangle icon on it), one of the attempts to reconnect eventually causes HexChat to crash.  I come back to see hexchat white and crashed.

Sometimes, my tether crashes because of a memory leak, on the phone's end, though currently active connections keep working because all clockworkmod does is route things like a router.  Once routed, they no longer need the app.  So at night time when I'm asleep, if say my phone loses signal for a short duration of time, but tether is still working and everything, HexChat crashes and I wake up to a white screened HexChat.  While sometimes if HexChat loses connection before I restart the crashed tether app, it crashes by the time my tether is restarted.

So the problem appears to be something related to reconnecting.  If you can give me a debug mode tool, or tell me how to enable crash logs, I will do so to get you a detailed report.

**Comment by Arnavion** [comment] 2015-10-26 09:36
Duplicate of #600

**Closed by Arnavion** 2015-10-26 09:36 UTC
